"""
context_change.py

Represents a contextual change detected between two consecutive
belief states.

Generated by the Context Monitoring Agent and consumed by the
Drift Detection Agent.
"""

from dataclasses import dataclass


@dataclass
class ContextChange:
    """
    Represents a single contextual change.
    """

    # ---------------------------------------------------------
    # Location
    # ---------------------------------------------------------

    turn_id: int

    domain: str

    slot: str

    # ---------------------------------------------------------
    # Values
    # ---------------------------------------------------------

    old_value: str

    new_value: str

    # ---------------------------------------------------------
    # Type of change
    # ---------------------------------------------------------

    change_type: str

    # ---------------------------------------------------------
    # Confidence
    # ---------------------------------------------------------

    confidence: float = 1.0

    # ---------------------------------------------------------
    # Importance Weight
    # ---------------------------------------------------------

    importance: float = 1.0

    def __str__(self):

        return (
            f"[Turn {self.turn_id}] "
            f"{self.domain}.{self.slot} : "
            f"{self.old_value} → {self.new_value} "
            f"({self.change_type}) "
            f"| importance={self.importance:.2f}"
        )